"""
writer.py — Output file management: README.md, per-module docs, docs index.

Output structure inside the analyzed project:
  <project_root>/
  ├── README.md          ← main entry point, links to docs/
  └── docs/              ← per-module documentation
      ├── index.md       ← navigation index
      └── <mirrored source tree as .md files>
"""

from pathlib import Path

from src.utils import logger


# ──────────────────────────────────────────────
# README.md
# ──────────────────────────────────────────────

def write_readme(content: str, root: Path) -> Path:
    """Write README.md to the project root."""
    out = root / "README.md"
    out.write_text(content, encoding="utf-8")
    logger.info(f"✔  README.md → {out}")
    return out


# ──────────────────────────────────────────────
# Per-module docs
# ──────────────────────────────────────────────

def write_module_doc(
    file_path: Path,
    content: str,
    root: Path,
    docs_dir: Path,
) -> Path:
    """
    Mirror the source file path inside docs/ as a .md file.

    Example:
        src/scanner.py  →  docs/src/scanner.md
    """
    relative = file_path.relative_to(root)
    out_path = docs_dir / relative.with_suffix(".md")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    header = f"# `{relative}`\n\n> *Auto-generated by ai-doc-gen*\n\n---\n\n"
    out_path.write_text(header + content, encoding="utf-8")
    logger.debug(f"  doc written → {out_path.relative_to(root)}")
    return out_path


# ──────────────────────────────────────────────
# docs/index.md
# ──────────────────────────────────────────────

def write_docs_index(
    doc_files: list[Path],
    docs_dir: Path,
    root: Path,
) -> Path:
    """
    Generate docs/index.md with a sorted navigation list
    linking to every generated module doc.
    """
    lines: list[str] = [
        "# Documentation Index\n",
        "> *Auto-generated by ai-doc-gen*\n\n",
        "## Modules\n",
    ]

    for doc in sorted(doc_files):
        rel_from_docs = doc.relative_to(docs_dir)
        label = str(rel_from_docs.with_suffix(""))   # e.g. src/scanner
        lines.append(f"- [{label}]({rel_from_docs})\n")

    index_path = docs_dir / "index.md"
    index_path.write_text("".join(lines), encoding="utf-8")
    logger.info(f"✔  docs/index.md → {index_path}")
    return index_path


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

def ensure_docs_dir(docs_dir: Path) -> None:
    """Create docs directory (and any parents) if it doesn't exist."""
    docs_dir.mkdir(parents=True, exist_ok=True)
    logger.debug(f"Docs directory ready: {docs_dir}")
